// <auto-generated />
using System;
using HQsAppWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HQsAppWeb.Data.Migrations
{
    [DbContext(typeof(ComicShopDbContext))]
    [Migration("20231205154540_AdicionarTabelaEditora")]
    partial class AdicionarTabelaEditora
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuimasBurguerAppWeb.Models.HQ", b =>
            {
                b.Property<int>("HQId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HQId"));

                b.Property<DateTime>("DataCadastro")
                    .HasColumnType("datetime2");

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<bool>("EntregaExpressa")
                    .HasColumnType("bit");

                b.Property<string>("ImagemUri")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("EditoraId")
                    .HasColumnType("int");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<double>("Preco")
                    .HasColumnType("float");

                b.HasKey("HQId");

                b.HasIndex("EditoraId");

                b.ToTable("HQ");
            });

            modelBuilder.Entity("GuimasBurguerAppWeb.Models.Editora", b =>
            {
                b.Property<int>("EditoraId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EditoraId"));

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("EditoraId");

                b.ToTable("Editora");
            });

            modelBuilder.Entity("GuimasBurguerAppWeb.Models.HQ", b =>
            {
                b.HasOne("GuimasBurguerAppWeb.Models.Editora", null)
                    .WithMany("HQs")
                    .HasForeignKey("EditoraId");
            });

            modelBuilder.Entity("GuimasBurguerAppWeb.Models.Editora", b =>
            {
                b.Navigation("HQs");
            });
#pragma warning restore 612, 618
        }
    }
}
