// <auto-generated />
using System;
using HQsAppWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HQsAppWeb.Data.Migrations
{
    [DbContext(typeof(ComicShopDbContext))]
    [Migration("20231205155417_AdicionarTabelaCategoria")]
    partial class AdicionarTabelaCategoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoriaHQ", b =>
            {
                b.Property<int>("CategoriasCategoriaId")
                    .HasColumnType("int");

                b.Property<int>("HQsHQId")
                    .HasColumnType("int");

                b.HasKey("CategoriasCategoriaId", "HQsHQId");

                b.HasIndex("HQsHQId");

                b.ToTable("CategoriaHQ");
            });

            modelBuilder.Entity("HQsAppWeb.Models.Categoria", b =>
            {
                b.Property<int>("CategoriaId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("CategoriaId");

                b.ToTable("Categoria");
            });

            modelBuilder.Entity("HQsAppWeb.Models.Editora", b =>
            {
                b.Property<int>("EditoraId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EditoraId"));

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("EditoraId");

                b.ToTable("Editora");
            });

            modelBuilder.Entity("HQsAppWeb.Models.HQ", b =>
            {
                b.Property<int>("HQId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HQId"));

                b.Property<DateTime>("DataCadastro")
                    .HasColumnType("datetime2");

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("EditoraId")
                    .HasColumnType("int");

                b.Property<bool>("EntregaExpressa")
                    .HasColumnType("bit");

                b.Property<string>("ImagemUri")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("Preco")
                    .HasColumnType("float");

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("HQId");

                b.HasIndex("EditoraId");

                b.ToTable("HQ");
            });

            modelBuilder.Entity("CategoriaHQ", b =>
            {
                b.HasOne("HQsAppWeb.Models.Categoria", null)
                    .WithMany()
                    .HasForeignKey("CategoriasCategoriaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("HQsAppWeb.Models.HQ", null)
                    .WithMany()
                    .HasForeignKey("HQsHQId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("HQsAppWeb.Models.HQ", b =>
            {
                b.HasOne("HQsAppWeb.Models.Editora", null)
                    .WithMany("HQs")
                    .HasForeignKey("EditoraId");
            });

            modelBuilder.Entity("HQsAppWeb.Models.Editora", b =>
            {
                b.Navigation("HQs");
            });
#pragma warning restore 612, 618
        }
    }
}
